syntax off
set synmaxcol=200
filetype plugin indent on

set encoding=utf-8
set ruler smartindent
set wrap linebreak nolist nojoinspaces
set nobackup noswapfile nowritebackup
set noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
set textwidth=80 formatoptions-=t formatoptions+=j
set showcmd showmode hidden
set magic matchtime=2 lazyredraw
set incsearch ignorecase smartcase showmatch hlsearch
set mouse=
set rulerformat=%22(%l,%c%V\ %o\ %p%%%)
set autoread laststatus=2

if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
	set t_Co=16
endif
set background=dark
colorscheme solarized

noremap <F1> <nop>
noremap Q <nop>
noremap K <nop>

set shortmess+=I
set noerrorbells novisualbell t_vb=

imap ^? ^H

set ttimeout timeoutlen=300 ttimeoutlen=0
set scrolloff=4

set wildignore=*.pyc,*.o,*.so,*.a
au BufReadPost fugitive://* set bufhidden=delete

let mapleader = ","

nnoremap <F9> 3<C-W><
nnoremap <F10> 3<C-W>+
nnoremap <F11> 3<C-W>-
nnoremap <F12> 3<C-W>>

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <F5> :%!xxd -g 1<CR>
nnoremap <F6> :%!xxd -g 1 -r<CR>

au BufEnter COMMIT_EDITMSG silent syntax on
au BufEnter neomutt-* silent syntax on
au BufEnter neomutt-* silent setl ft=mail tw=72 fo+=tn comments+=fb:*
au BufEnter neomutt-* silent /^$

au BufEnter *.gunk         silent setl ft=go
au BufEnter testdata/*.txt silent setl ft=go

nnoremap <space> :noh<cr>:echo<cr><esc>

vnoremap <leader>y "+y
nnoremap <leader>p "+p

inoremap <F8> Daniel Martí <mvdan@mvdan.cc>
