icons = "awesome5"

[theme]
name = "plain"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "networkmanager"

[[block]]
block = "net"
#device = "lo"
speed_up = true
interval = 2
#format = "{speed_up} {speed_down}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 2

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 2
#format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "load"
interval = 2
format = "{1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
