icons = "awesome5"

[theme]
name = "plain"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "networkmanager"
on_click = "termite -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/mvdan/mail/mvdan/Inbox", "/home/mvdan/mail/mvdan/Other", "/home/mvdan/mail/mvdan/Go", "/home/mvdan/mail/protocol/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "net"
device = "wlan0"
speed_up = true
interval = 2
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "ens8u2"
speed_up = true
interval = 2
hide_missing = true
hide_inactive = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 2

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 2
#format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "load"
interval = 2
format = "{1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
