#!/bin/bash

# For the Logitech c920.
# power_line_frequency: UK/EU power line frequency, 50hz.
# focus_automatic_continuous,focus_absolute: Disable autofocus, manually set to 65 for my face.
# white_balance_automatic,white_balance_temperature: Manually set to 4800 (mildly warm).

# Briefly tried auto_exposure=1,exposure_time_absolute=199 which was better in
# most cases, but unfortunately broke power_line_frequency.

dev_video_by_name() {
	for n in {0..3}; do
		dev=/dev/video$n
		if v4l2-ctl --info --device $dev | grep -q "Name.*:.*$@"; then
			echo $dev
			return
		fi
	done
	echo "unknown"
}

/usr/bin/v4l2-ctl \
	--set-ctrl=power_line_frequency=1,focus_automatic_continuous=0,focus_absolute=60,auto_exposure=3,white_balance_automatic=0,white_balance_temperature=4800 \
	--device $(dev_video_by_name C920)
