#!/bin/bash

if [[ $# -lt 1 ]]; then
	echo 'e.g: foreach go-modules go mod tidy'
	exit 1
fi

cmd=$1
shift

for dir in $($cmd); do
	(
		echo $dir
		cd $dir
		eval "$@" # allow multiple commands like "foo && bar"
	)
done
