#!/bin/bash

if [[ $# == 0 || $1 == help ]]; then
	echo "gbench [cur] [.] [6] [1s] [flags]"
	exit 1
fi
go test . -run='^$' -vet=off -bench=${2:-.} \
	-count=${3:-6} -benchtime=${4:-1s} ${@:5} | tee ${1:-cur} | grep -vE ': |truncated]'
