#!/bin/bash

pkgs="${@:-.}"

{
	go tool vet --shadow=true $pkgs &
	errcheck $pkgs | sed 's/$/ returns error/' &
	unused $pkgs &
	golint $pkgs | grep -vE 'or be unexported' &
	unconvert $pkgs &
	maligned $pkgs &
	ineffassign $pkgs &
	interfacer $pkgs &
	gosimple $pkgs &
	staticcheck $pkgs &
} |& grep -v 'vendor/' | sed -r 's/(: |\t)/:\t/'
