#!/bin/bash

# go-cross [go binary] [version]

gocmd=${1:-"go"}
version=${2:-$(git describe --always --dirty --tags)}
dir=$(basename "$PWD")

echo "Building version ${version} with $($gocmd version)"

while read goos goarch; do
	(
		export GOOS=$goos GOARCH=$goarch
		out="${dir}_${version}_${goos}_${goarch}$(go env GOEXE)"
		GOOS=$goos GOARCH=$goarch CGO_ENABLED=0 go build -trimpath -ldflags="-w -s -X 'main.version=${version}'" -o=${out}
		echo $out
	) &
done <<-EOF # Hard-code the list for now, until https://golang.org/issues/38874 is fixed.
	linux amd64
	linux 386
	linux arm
	linux arm64
	darwin amd64
	windows amd64
	windows 386
EOF

wait
