#!/bin/bash

set -e

export GO111MODULE=on

installs=(
	# golang.org
	golang.org/x/review/git-codereview
	golang.org/x/tools/cmd/goimports
	golang.org/x/tools/cmd/present
	golang.org/x/tools/cmd/stress
	golang.org/x/tools/cmd/stringer
	golang.org/x/tools/cmd/toolstash
	golang.org/x/tools/cmd/compilebench
	golang.org/x/perf/cmd/benchstat
	golang.org/x/lint/golint

	# mvdan.cc
	mvdan.cc/sh/cmd/shfmt
	mvdan.cc/fdroidcl
	mvdan.cc/goreduce
	mvdan.cc/unparam
	mvdan.cc/gogrep
	mvdan.cc/git-picked
	mvdan.cc/xurls/v2/cmd/xurls

	# dev tools
	github.com/dvyukov/go-fuzz/go-fuzz
	github.com/dvyukov/go-fuzz/go-fuzz-build
	github.com/mitchellh/gox
	github.com/aclements/perflock/cmd/perflock
	github.com/aclements/go-misc/benchcmd
	github.com/rogpeppe/go-internal/cmd/testscript

	# misc
	github.com/hanwen/go-mtpfs
	github.com/astaxie/bat

	# linters
	github.com/mdempsky/unconvert
	github.com/mdempsky/maligned
	github.com/mibk/dupl
	honnef.co/go/tools/cmd/staticcheck
	honnef.co/go/tools/cmd/errcheck-ng
)

go get -ldflags="-w -s" "${installs[@]}"
