#!/bin/bash

pkgs=(
	# golang.org
	golang.org/x/review/git-codereview
	golang.org/x/tools/cmd/godoc
	golang.org/x/tools/cmd/goimports
	golang.org/x/tools/cmd/stress
	golang.org/x/tools/cmd/present

	# vendoring
	github.com/FiloSottile/vendorcheck
	github.com/FiloSottile/gvt

	# github.com/mvdan
	github.com/mvdan/xurls/cmd/xurls
	github.com/mvdan/sh/cmd/shfmt
	github.com/mvdan/interfacer/cmd/interfacer

	# gopath
	github.com/shurcooL/Go-Package-Store/cmd/Go-Package-Store
	github.com/shurcooL/gostatus

	# building
	github.com/mitchellh/gox

	# bench
	rsc.io/benchstat

	# fuzz
	github.com/dvyukov/go-fuzz/go-fuzz
	github.com/dvyukov/go-fuzz/go-fuzz-build

	# misc
	github.com/hanwen/go-mtpfs

	# linters
	github.com/kisielk/errcheck
	github.com/golang/lint/golint
	github.com/mdempsky/unconvert
	github.com/mdempsky/maligned
	github.com/gordonklaus/ineffassign
	honnef.co/go/simple/cmd/gosimple
	honnef.co/go/unused/cmd/unused
	honnef.co/go/staticcheck/cmd/staticcheck
)

go install -v "${pkgs[@]}"
