#!/bin/bash

pkgs=(
	# golang.org
	golang.org/x/review/git-codereview
	golang.org/x/tools/cmd/goimports
	golang.org/x/tools/cmd/present
	golang.org/x/tools/cmd/stress
	golang.org/x/tools/cmd/stringer
	golang.org/x/perf/cmd/benchstat

	# github.com/mvdan
	github.com/mvdan/xurls/cmd/...
	github.com/mvdan/sh/cmd/...
	github.com/mvdan/interfacer/cmd/...
	github.com/mvdan/unparam
	github.com/mvdan/git-picked
	github.com/mvdan/fdroidcl/cmd/...
	github.com/mvdan/lint/cmd/...

	# gopath
	github.com/shurcooL/Go-Package-Store/cmd/...

	# dev tools
	github.com/dvyukov/go-fuzz/go-fuzz
	github.com/dvyukov/go-fuzz/go-fuzz-build
	github.com/mitchellh/gox
	github.com/FiloSottile/vendorcheck
	github.com/FiloSottile/gvt
	github.com/kardianos/govendor

	# misc
	github.com/hanwen/go-mtpfs
	github.com/astaxie/bat
	github.com/davecheney/httpstat
	npf.io/gorram

	# linters
	github.com/golang/lint/golint
	github.com/mdempsky/unconvert
	github.com/mdempsky/maligned
	github.com/mibk/dupl
	honnef.co/go/tools/cmd/megacheck
	honnef.co/go/tools/cmd/gosimple
	honnef.co/go/tools/cmd/unused
	honnef.co/go/tools/cmd/staticcheck
	honnef.co/go/tools/cmd/errcheck-ng
)

go install -v -ldflags="-w -s" "${pkgs[@]}"
