#!/bin/bash

export GOFLAGS="-trimpath"
export CGO_ENABLED=0

gocmd=${1:-"/usr/bin/go"}
version=$(git describe --always --dirty)

$gocmd version
echo "Building at $version"

gox -gocmd="$gocmd" -ldflags="-w -s -extldflags '-static' -X 'main.version=$version'" -parallel=2 -output="{{.Dir}}_$(git describe)_{{.OS}}_{{.Arch}}"
