#!/bin/bash

export GOFLAGS="-trimpath"
export CGO_ENABLED=0

gocmd=${1:-"/usr/bin/go"}
echo "Using $gocmd"

gox -gocmd="$gocmd" -ldflags='-w -s' -parallel=2 -output="{{.Dir}}_$(git describe)_{{.OS}}_{{.Arch}}"
