input type:keyboard {
	xkb_layout  us,es
	xkb_variant altgr-intl,cat
	xkb_options caps:escape,grp:alt_space_toggle
}

input type:touchpad {
	tap  enabled
	drag enabled
	dwt  enabled # disable while typing

	scroll_method  two_finger
	natural_scroll enabled
	pointer_accel  0.6
	click_method   clickfinger # 2/3 fingers is right/middle click
}

input type:pointer {
	pointer_accel 1.0
	scroll_factor 1.5
}
