# Apps

bindsym $mod+Alt+k exec $term --app-id=nnn nnn -d -u -U
bindsym $mod+Alt+e exec $term hx Documents/TODO.txt
bindsym $mod+Alt+j exec flatpak run org.mozilla.thunderbird
bindsym $mod+Alt+i exec flatpak run org.mozilla.firefox -P default
bindsym $mod+Alt+n exec flatpak run org.strawberrymusicplayer.strawberry

# Other custom binds

# bindsym $mod+g exec grim - | swappy -f -                   # all displays + swappy
bindsym $mod+Shift+g exec grim -g "$(slurp)" - | swappy -f - # slurp + swappy, screenshot an area and edit it
bindsym $mod+Alt+g exec cd /tmp && grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') # current dislay + /tmp
bindsym $mod+o exec killall -SIGUSR1 waybar
bindsym $mod+p exec wofimoji --selector rofi --selector-args -dmenu

bindsym $mod+Shift+p exec systemctl poweroff
bindsym --locked $mod+Shift+s exec systemctl suspend
bindsym $mod+Shift+o exec "swaylock -f; sleep 1; pkill -USR1 swayidle"
