# Minor tweaks to Go, like gopls flags.
[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "-remote=auto", "serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }

# "cue fmt" is buggy.
[[language]]
name = "cue"
auto-format = false

# Indent shell with tabs.
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

# Indent markdown with tabs.
[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }
