# Minor tweaks to Go, like gopls flags.
[language-server.gopls]
command = "gopls"
args = ["serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.cuelsp]
command = "cue"
args = ["lsp", "serve"]

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cue"
# "cue fmt" is buggy.
# auto-format = false
language-servers = ["cuelsp"]

# Indent shell with tabs.
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

# Indent markdown with tabs.
[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }
